services:
  qgis:
    build:
      context: ./qgis
      args:
        QGIS_CHANNEL: ubuntu-ltr
    container_name: qgis
    ports:
    - 3389:3389
    restart: unless-stopped
    volumes:
    - ./data/qgis-projects:/home/qgis/qgis-projects
    - ./data/qgis-config/.local/share/QGIS:/home/qgis/.local/share/QGIS
    - ./data/qgis-config/.config/QGIS:/home/qgis/.config/QGIS
    - shared-transfer:/tmp/transfer
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    volumes:
    - shared-transfer:/tmp/transfer
    restart: unless-stopped
  mysql:
    build:
      context: ./mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacpass
      GUACADMIN_USER: guacadmin
      GUACADMIN_PASS: guacadmin
      GUAC_USER: myuser
      GUAC_PASS: mypass123
    volumes:
    - ./data/mysql:/var/lib/mysql
  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacpass
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
    - guacd
    - mysql
volumes:
  shared-transfer: